config/routes.rb
FullAjaxTest::Application.routes.draw do
  resources :memos

end

app/models/memo.rb
class Memo < ActiveRecord::Base
  attr_accessible :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memos }
    end
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
    @memo = Memo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @memo }
    end
  end

  # GET /memos/new
  # GET /memos/new.json
  def new
    @memo = Memo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @memo }
    end
  end

  # GET /memos/1/edit
  def edit
    @memo = Memo.find(params[:id])
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(params[:memo])

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render json: @memo, status: :created, location: @memo }
      else
        format.html { render action: "new" }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memos/1
  # PUT /memos/1.json
  def update
    @memo = Memo.find(params[:id])

    if @memo.update_attributes(params[:memo])
      status = 'success'
    else
      status = 'error'
    end

    render json: { status: status, data: @memo }
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy

    respond_to do |format|
      format.html { redirect_to memos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FullAjaxTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/memos/_form.html.erb
<%= form_for memo, remote: true do |f| %>
    <%= f.text_field :body, id: nil, class: 'body' %>
    <%= f.submit 'Update' %>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing memo</h1>

<%= render 'form' %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<h1>Listing memos</h1>

<div id="memos">
    <% @memos.each do |memo| %>
        <div class="memo">
            <div class="viewer">
                <span class="body"><%= memo.body %></span>
                <%= button_tag 'Edit', class: 'edit', type: :button %>
            </div>
            <div class="editor">
                <div>
                    <%= button_tag 'Cancel', class: 'cancel', type: :button %>
                </div>
                <%= render 'form', memo: memo %>
            </div>
        </div>
    <% end %>
</div>

<br />

<%= link_to 'New Memo', new_memo_path %>

app/views/memos/new.html.erb
<h1>New memo</h1>

<%= render 'form' %>

<%= link_to 'Back', memos_path %>

app/views/memos/org_form.html.erb
<%= form_for(@memo) do |f| %>
  <% if @memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% @memo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memos/org_index.html.erb
<h1>Listing memos</h1>

<table>
  <tr>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memos.each do |memo| %>
  <tr>
    <td><%= memo.body %></td>
    <td><%= link_to 'Show', memo %></td>
    <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
    <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Memo', new_memo_path %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @memo.body %>
</p>


<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>